### ISSUE TITLE
How to flash?

### ISSUE THREAD

**Issue by ME1234568** [PizzaG/android_device_blu_B130DL#1]
Hello everyone,

I was wondering how to flash this as this device doesn't have fastboot, and the twrp app doesn't allow flashing unofficial images. Could someone put it in step by step instructions for me as I am kind of slow when it comes to people trying to explain things to me. The device already has an unlocked bootloader. Thanks!

**Comment by PizzaG** [comment]
If you already have root, you could pry use an app like Flashify to flash recovery.  If you don't have root, You will want to use MtkClient to flash the recovery image to recovery partition of the device.  Keep in mind that you can dump, pacth your boot image with Magisk and flash root that way as well.  

You can find MtkClient here:
https://github.com/bkerler/mtkclient

Do your best and if you can't figure it out, get ahold of me live on Telegram and we can Teamview or something and I'll give you a hand

Telegram Link
https://t.me/Android_General_Chat

**Comment by ME1234568** [comment]
Thanks, I'll take a look and see if I can figure it out. So far can't find anything about flashing .img files (stuff about flashing .bins and the like).

**Comment by PizzaG** [comment]
> Thanks, I'll take a look and see if I can figure it out. So far can't find anything about flashing .img files (stuff about flashing .bins and the like).

you can simply take a recovery.bin file and rename it recovery.img and it will be fine
